#all important paramters together

NUMBER_OF_RECOMMENDATION = 7

# IN ONE_HOT ENCODING - WHAT IS MINUMUM PERCENTAGE OF DATA IF NOT LABEL AS 'OTHER'
TRESHOLD_OF_MINIMUM_OCCURENCE = 0.0001

# MINIMUM VALUE OF PROBABILITY IF WE WANT RECOMMEND PRODUCT FOR USER
MIN_PROB_THRESHOLD_FOR_RECOMMENDATION = 0.3

# RANOM FORREST PARAMS
RANDOM_FORREST_NUMBER_OF_TREE = 150
RANDOM_FORREST_MAX_FEATURES = "log2"